<ol class="breadcrumb">
  <li><a href="/admin.php/home">首页</a></li>
  <li class="active">编辑栏目</li>
</ol>

<div class="col-sm-2 col-sm-offset-1">
	<h3>编辑栏目</h3>
</div>

<div class="clearfix"></div>
<div class="col-sm-8">
	<form class="form-horizontal" role="form" method="post">
		<div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">分类选择</label>
	    <div class="col-sm-2">
	      <select name="category" class="form-control">
	      	<?php foreach($categories as $category):?>
	      	<option value="<?php echo $category['id'];?>"><?php echo $category['name'];?></option>
	      	<?php endforeach;?>
	      </select>
	    </div>
	  </div>
	  <div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">名称</label>
	    <div class="col-sm-2">
	      <input type="text" name="name" class="form-control" id="" value="<?php echo $name; ?>" placeholder="">
	    </div>
	  </div>
	  <div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">故事介绍</label>
	    <div class="col-sm-2">
	      <textarea name="story" class="form-control" rows="3"><?php echo $story; ?></textarea>
	    </div>
	  </div>
	  <div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">栏目封面</label>
	    <div class="col-sm-2">
	      <input type="file" id="" name="cover">
	    </div>
	  </div>
	  <div class="form-group">
	  	<div class="col-sm-offset-2 col-sm-2">
			  <div class="checkbox">
			    <label>
			      <input type="checkbox" name="end"> 已完结
			    </label>
			  </div>
			</div>
		</div>
	  <div class="form-group">
	  	<div class="col-sm-offset-2 col-sm-2">
			  <div class="checkbox">
			    <label>
			      <input type="checkbox" name="tv" <?php if($isTv):?>checked<?php endif;?>> TV版
			    </label>
			  </div>
			</div>
		</div>
		<div id="tv-form" <?php if(!$isTv):?>class="hidden"<?php endif;?>>
		  <div class="form-group">
		    <label for="inputEmail3" class="col-sm-2 control-label">第几季</label>
		    <div class="col-sm-2">
		      <input type="text" name="tvseason" class="form-control" id="" value="<?php echo $tvseason; ?>" placeholder="">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="inputEmail3" class="col-sm-2 control-label">播出日</label>
		    <div class="col-sm-2">
		      <input type="text" name="tvrelease" class="form-control" id="" value="<?php echo $tvrelease; ?>" placeholder="">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="inputEmail3" class="col-sm-2 control-label">每周几更新</label>
		    <div class="col-sm-2">
		      <input type="text" name="tvday" class="form-control" id="" value="<?php echo $tvday; ?>" placeholder="">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="inputEmail3" class="col-sm-2 control-label">共几集</label>
		    <div class="col-sm-2">
		      <input type="text" name="tvnumber" class="form-control" id="" value="<?php echo $tvnumber; ?>" placeholder="">
		    </div>
		  </div>
		</div>
	  <div class="form-group">
	  	<div class="col-sm-offset-2 col-sm-2">
			  <div class="checkbox">
			    <label>
			      <input type="checkbox" name="ova" <?php if($isOva):?>checked<?php endif;?>> OVA版
			    </label>
			  </div>
			</div>
		</div>
		<div id="ova-form" <?php if(!$isOva):?>class="hidden"<?php endif;?>>
		  <div class="form-group">
		    <label for="inputEmail3" class="col-sm-2 control-label">共几集</label>
		    <div class="col-sm-2">
		      <input type="text" name="ovanumber" class="form-control" id="" value="<?php echo $ovanumber; ?>" placeholder="">
		    </div>
		  </div>
		</div>
	  <div class="form-group">
	    <div class="col-sm-offset-2 col-sm-2">
	      <button type="submit" class="btn btn-default">保存</button>
	    </div>
	  </div>
	</form>
</div>
<script>
$(function(){
	$("input[name=tv]").change(function(){
		if($(this).is(':checked') == true)
		{
			$('#tv-form').removeClass("hidden");
		}else{
			$('#tv-form').addClass("hidden");
		}
	});

	$("input[name=ova]").change(function(){
		if($(this).is(':checked') == true)
		{
			$('#ova-form').removeClass("hidden");
		}else{
			$('#ova-form').addClass("hidden");
		}
	});
})
</script>
