<div class="container-fluid">
	<div class="row">
		<div class="col-sm-2 col-sm-offset-1">
			<h3>Login backoffice</h3>
		</div>
		<div class="clearfix"></div>
		<div class="col-sm-8">
			<form class="form-horizontal" role="form" method="post">
			  <div class="form-group">
			    <label for="inputEmail3" class="col-sm-2 control-label">Username</label>
			    <div class="col-sm-2">
			      <input type="text" name="username" class="form-control" id="inputEmail3" placeholder="">
			    </div>
			  </div>
			  <div class="form-group">
			    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
			    <div class="col-sm-2">
			      <input type="password" name="password" class="form-control" id="inputPassword3" placeholder="">
			    </div>
			  </div>
			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-2">
			      <button type="submit" class="btn btn-default">Login</button>
			    </div>
			  </div>
			</form>
		</div>
		<?php var_dump(Yaf\Session::getInstance()->get("Authentication")); ?>
	</div>
</div>