<div class="container-fluid">
	<div class="row">
		<div class="col-sm-2 col-sm-offset-1">
			<h3>编辑栏目分类</h3>
		</div>
		<div class="clearfix"></div>
		<div class="col-sm-8">
			<form class="form-horizontal" role="form" method="post">
			  <div class="form-group">
			    <label for="inputEmail3" class="col-sm-2 control-label">栏目名称</label>
			    <div class="col-sm-2">
			      <input type="text" name="name" class="form-control" id="inputEmail3" placeholder="">
			    </div>
			  </div>
			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-2">
			      <button type="submit" class="btn btn-default">保存</button>
			    </div>
			  </div>
			</form>
		</div>
	</div>
</div>